---
apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
    - image: gcr.io/td-jcase/jcase
#      context: .
#      jibGradle: {}
deploy:
  kubectl:
    manifests:
      - deployment/k8s-*
