#!/bin/sh

set -e
set -x

echo "Running ShellCheck"
#find .circleci/scripts/ -type f -exec shellcheck {} +

echo "Running Google Java Style audit"
find src/ -type f -name "*.java" -exec java -jar .circleci/scripts/validate/checkstyle-8.13-all.jar -c .circleci/scripts/validate/google_checks.xml {} +

#find scripts/ -type f | grep -v scripts/winresources | xargs shellcheck

set +x
